name: prompty Python build and publish

on:
  push:
    paths:
      - 'runtime/prompty/**'
    tags:
      - 'python/*'
  workflow_dispatch:


env:
  AZURE_OPENAI_ENDPOINT: https://fake
  AZURE_OPENAI_KEY: 12342323433
  

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: 3.11.5

      - name: install dependencies
        working-directory: ./runtime/prompty
        run: pdm install

      - name: test package
        working-directory: ./runtime/prompty
        run: pdm run pytest

      - name: Publish package distributions to PyPI
        working-directory: ./runtime/prompty
        run: pdm publish
